### ISSUE TITLE
UI on login page is not responsive to iphone 4s screen size

### ISSUE THREAD

**Issue by pravipati** [crewapp/crewapp#138]
# Explain the bug

The user interface elements on the login page are not responsive in design and thus are partially cropped out when rendered on the iphone 4s screen. 
# Steps to reproduce

Run latest build of crew iOS app in xcode using the iphone 4s emulator
# Screenshots

![screen shot 2015-04-17 at 1 58 00 pm](https://cloud.githubusercontent.com/assets/410195/7210879/61148ad4-e50a-11e4-8dac-ca53b196c8a8.png)

**Comment by pravipati** [comment]
Another issue: the chatroom won't display messages in the the view when running app with the iphone 4s emulator but messages will display when the app is rendered with the iphone 6 emulator.

**Comment by arianf** [comment]
This is fine, I think the 3.5 screen is deprecated anyways, this could be added later

**Comment by pravipati** [comment]
@arianf Ok. Just a heads up--it also cuts the bottom of the create account button in the 5s simulator (still useable though). I opened this issue as a placeholder to go back and change the design of the buttons to be responsive to the screen.

**Comment by arianf** [comment]
Okay, sounds good!
