### ISSUE TITLE
Transition to Ionic

### ISSUE THREAD

**Issue by rkho** [crewapp/crewapp#151]
The following things need to be done to transition our front-end to Ionic:
- Splash Page
  - Log In + Create Account buttons
    - Clicking on these buttons directs the user to their views
- Log In Page
  - Contains Username and Password fields
  - Submit button
    - When pressed, checks the entered fields against the MySQL database. If it's a success, we route to the ChatRoom view. Otherwise we return an error alert.
- Create Account
  - Same fields as Log In Page
    - When submitted, checks to see if the username already exists in the database. If it does not, we route to the ChatRoom view. Otherwise we return an error.
- Chat Room
  - A chatbox on top
  - Message field with send button
  - A 'Make Event' button that takes you to the view.
## Extras
- Make Event
  - A search field (hopefully Google Places or something) that will let users add an event/place, address, time, and date
  - When submitted, sends it to Chat Room (and returns users to Chat Room)

**Comment by arianf** [comment]
#153
