### ISSUE TITLE
Get realtime sockets based middleware to integrate with React-native

### ISSUE THREAD

**Issue by koziscool** [crewapp/crewapp#44]
So far we've looked at RabbitMQ and Pubnub but the integration with React-native is a separate obstacle.

React-native isn't instigated with an html file so we can't script-tag include the pubnub lib.  Intuitively I thought that we should use node instead since there is support for pubnub with node.

But, react-native doesn't support node runtime.  Therefore our current idea is to create a polyfill (or duplicate functionality for a context that's not supported) for WebSockets with react-native.  Pubnub realtime message functionality is a wrapper around WebSockets so hopefully we could use that or maybe some other publish-subscribe functionality around that.

**Comment by pravipati** [comment]
There's an [issue](https://github.com/facebook/react-native/issues/619) currently open in react-native's repository that talks about a websocket api polyfill.

We have a few different options that we can explore:
1. We can take a look at some of the community's websocket polyfills. The ones I took a cursory look at seem to have memory leak bugs but it's at least worth investigating.
2. We can try and create our own polyfill for native's fetch function to add parsing functionality and then bring in PubNub via cdn.
3. We can explore XHR polling with socket.io.
