### ISSUE TITLE
Signup view

### ISSUE THREAD

**Issue by koziscool** [crewapp/crewapp#87]
Initial screen for app.  Takes username, (created) password, maybe swipe on question.  Transitions to chat view.

**Comment by rkho** [comment]
I think this is really overscoped. Here are all the different views and components I'm seeing here:
- Sign-In View
  - Takes Username, Password
    - Sends information to database
- Questions View
  - Generates a list of questions, functionality to accept answers
  -  Sends answers to database

**Comment by rkho** [comment]
I'm closing this issue to refactor it.
