### ISSUE TITLE
Modularize react native components

### ISSUE THREAD

**Issue by pravipati** [crewapp/crewapp#95]
- [x] Separate components 
- [x] Create index.js and style.js for each component
- [ ] Create Utils folder for reusable functions

Example structure:

![screen shot 2015-04-13 at 10 41 22 am](https://cloud.githubusercontent.com/assets/410195/7121502/c18e4d26-e1c9-11e4-98e7-0eaddea5bbcd.png)

**Comment by arianf** [comment]
@pravipati why didn't you check the stuff off?

**Comment by pravipati** [comment]
@rkho took over this issue

**Comment by arianf** [comment]
Is this @rkho ?
